version: 0.2

phases:
  install:
    commands:
      - echo "Installing boto3"
      - rm -rf venv && mkdir venv
      - pip install virtualenv
      - virtualenv venv/
      - . venv/bin/activate
      - pip install boto3
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - echo "build"
  post_build:
    commands:
      - echo "Cleaning up"
      - python3 remove-old-bastion-amis.py

